Repository waellet/waellet, pull requests merged in 2020-02, with the labels that each got.

#271 #266: Added network configuration parameters
  src/popup/locales/cn.json
  src/popup/locales/de.json
  src/popup/locales/en.json
  src/popup/locales/es.json
  src/popup/locales/fr.json
  src/popup/locales/it.json
  src/popup/locales/ru.json
  src/popup/router/pages/ManageNetworks.vue
Labels: status/review

#281 Remove unused imports, Minify CSS. Create variables.scss. Replace all imports of common.scss with variables.scsss
  package-lock.json
  src/background.js
  src/common/base.scss
  src/common/variables.scss
  src/lib/wallet.js
  src/popup/popup.html
  src/popup/router/components/AddressInput.vue
  src/popup/router/components/Alert.vue
  src/popup/router/components/AmountInput.vue
  src/popup/router/components/Loader.vue
  src/popup/router/components/Modal.vue
  src/popup/router/components/NodeConnectionStatus.vue
  src/popup/router/components/TransactionItem.vue
  src/popup/router/index.js
  src/popup/router/pages/AboutSettings.vue
  src/popup/router/pages/Account.vue
  src/popup/router/pages/AccountPassword.vue
  src/popup/router/pages/AddFungibleToken.vue
  src/popup/router/pages/AdvancedSettings.vue
  src/popup/router/pages/AirGapSetup.vue
  src/popup/router/pages/Allowances.vue
  src/popup/router/pages/AuctionBid.vue
  src/popup/router/pages/ConnectConfirm.vue
  src/popup/router/pages/CreateFungibleToken.vue
  src/popup/router/pages/FungibleTokens.vue
  src/popup/router/pages/FungibleTokensPage.vue
  src/popup/router/pages/GeneralSettings.vue
  src/popup/router/pages/Index.vue
  src/popup/router/pages/LedgerSetup.vue
  src/popup/router/pages/ManageAccounts.vue
  src/popup/router/pages/ManageNetworks.vue
  src/popup/router/pages/MintFungibleToken.vue
  src/popup/router/pages/NamingSystem.vue
  src/popup/router/pages/PrivacyPolicy.vue
  src/popup/router/pages/QrCodeReader.vue
  src/popup/router/pages/Receive.vue
  src/popup/router/pages/SecuritySettings.vue
  src/popup/router/pages/SeedPhrase.vue
  src/popup/router/pages/Send.vue
  src/popup/router/pages/Settings.vue
  src/popup/router/pages/SignAndVerifyMsg.vue
  src/popup/router/pages/SignTransaction.vue
  src/popup/router/pages/SignTransactionByQrCode.vue
  src/popup/router/pages/TermsOfService.vue
  src/popup/router/pages/TipPage.vue
  src/popup/router/pages/TokenMigration.vue
  src/popup/router/pages/TokenMigrationInfo.vue
  src/popup/router/pages/TransactionDetails.vue
  src/popup/router/pages/Transactions.vue
  src/popup/router/pages/Utilities.vue
  src/popup/utils/address-generator.js
  src/popup/utils/constants.js
  src/popup/utils/hdWallet.js
  src/popup/utils/helper.js
  src/popup/utils/keystore.js
  src/popup/utils/ledger/ledger-bridge.js
  src/store/actions.js
  src/store/index.js
  webpack.config.js
Labels: status/review

#283 Fixing problem with Firefox injection of Aepp
  src/inject.js
  src/lib/wallet.js
  src/popup/router/pages/SignTransaction.vue
  src/popup/utils/connection.js
  src/popup/utils/helper.js
Labels: status/review

#288 Feature AEX-2
  package-lock.json
  package.json
  src/background.js
  src/inject.js
  src/lib/initEnv.js
  src/lib/popup-connection.js
  src/lib/rpcWallet.js
  src/lib/wallet.js
  src/manifests/manifest_chrome.json
  src/manifests/manifest_firefox.json
  src/notifications.js
  src/popup/App.vue
  src/popup/locales/en.json
  src/popup/popup-firefox.html
  src/popup/popup.js
  src/popup/router/components/Popup.vue
  src/popup/router/pages/AddFungibleToken.vue
  src/popup/router/pages/AdvancedSettings.vue
  src/popup/router/pages/Allowances.vue
  src/popup/router/pages/ManageAccounts.vue
  src/popup/router/pages/MintFungibleToken.vue
  src/popup/router/pages/Popups/PopupAskAccounts.vue
  src/popup/router/pages/Popups/PopupConnect.vue
  src/popup/router/pages/Popups/PopupSignTx.vue
  src/popup/router/pages/SignTransaction.vue
  src/popup/router/routes.js
  src/popup/utils/aepp-utils.js
  src/popup/utils/connection.js
  src/popup/utils/constants.js
  src/popup/utils/getPopupProps.js
  src/popup/utils/helper.js
  src/popup/utils/storage.js
  src/store/actions.js
  src/store/getters.js
  src/store/index.js
  src/store/mutation-types.js
  src/store/mutations.js
  src/wallet-controller.js
  webpack.config.js
Labels: status/review

#292 Feature AEX-2
  package-lock.json
  package.json
  src/background.js
  src/inject.js
  src/lib/initEnv.js
  src/lib/popup-connection.js
  src/lib/rpcWallet.js
  src/lib/wallet.js
  src/manifests/manifest_chrome.json
  src/manifests/manifest_firefox.json
  src/notifications.js
  src/popup/App.vue
  src/popup/locales/en.json
  src/popup/popup-firefox.html
  src/popup/popup.js
  src/popup/router/components/Popup.vue
  src/popup/router/pages/AddFungibleToken.vue
  src/popup/router/pages/AdvancedSettings.vue
  src/popup/router/pages/Allowances.vue
  src/popup/router/pages/ManageAccounts.vue
  src/popup/router/pages/MintFungibleToken.vue
  src/popup/router/pages/Popups/PopupAskAccounts.vue
  src/popup/router/pages/Popups/PopupConnect.vue
  src/popup/router/pages/Popups/PopupSignTx.vue
  src/popup/router/pages/SignTransaction.vue
  src/popup/router/routes.js
  src/popup/utils/aepp-utils.js
  src/popup/utils/connection.js
  src/popup/utils/constants.js
  src/popup/utils/getPopupProps.js
  src/popup/utils/helper.js
  src/popup/utils/storage.js
  src/store/actions.js
  src/store/getters.js
  src/store/index.js
  src/store/mutation-types.js
  src/store/mutations.js
  src/wallet-controller.js
  webpack.config.js
Labels: area/aepp, area/performance, area/sdk, kind/feature

#293 Use extendTtl for extending names
  src/popup/router/pages/NamingSystem.vue
  src/popup/router/pages/SignTransaction.vue
Labels: area/aens, status/review

#296 Fixing flashing message insufficient balance in popup
  src/popup/router/pages/SignTransaction.vue
Labels: area/contracts, status/review

#291 Deprecate advanced settings
  src/popup/router/pages/AdvancedSettings.vue
  src/popup/router/pages/SecuritySettings.vue
  src/popup/router/pages/Settings.vue
Labels: area/account, area/design
